server:
  port: 9003

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: comment-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  profiles:
    include: localdb

management:
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true

jwt:
  tokenValidTime: 1800000
  secret: COS-MOST-TEAM-SECRET-KEY

